### PR TITLE
Update list.json

### PR DESCRIPTION
**Pull request by gavin-aus**

### CODE REVIEW

**Comment by gavin-aus** [comment]
Adding a map

**Comment by tijmenvangulik** [comment]
thank you for the map

**Comment by tijmenvangulik** [comment]
Hi ,

Thank you for the map. I just merged the request. Hoever when I load the map  it gives an error. There seems to be something wrong with the kml file. Can you fix tis?

Tuhneb

**Comment by gavin-aus** [comment]
Yeah, I think it's my URL. I'm just trying to work out what the correct URL should be. -- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 13/4/20, 6:37 pm Tijmen van Gulik <notifications@github.com> wrote:

   Hi ,
   
   Thank you for the map. I just merged the request. Hoever when I load the map it gives an error. There seems to be something wrong with the kml file. Can you fix tis?
   
   Tuhneb

**Comment by tijmenvangulik** [comment]
You need the url to the raw file:

https://raw.githubusercontent.com/gavin-aus/Ergometerspace/master/data/maps/George%20Bass%20-%20Leg%201.kml <https://raw.githubusercontent.com/gavin-aus/Ergometerspace/master/data/maps/George%20Bass%20-%20Leg%201.kml>

**Comment by gavin-aus** [comment]
Ok, I've fixed up the url. It just needs to be merged-- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 13/4/20, 6:44 pm Tijmen van Gulik <notifications@github.com> wrote:

   You need the url to the raw file:
   
   https://raw.githubusercontent.com/gavin-aus/Ergometerspace/master/data/maps/George%20Bass%20-%20Leg%201.kml <https://raw.githubusercontent.com/gavin-aus/Ergometerspace/master/data/maps/George%20Bass%20-%20Leg%201.kml>

**Pull request merged**
